/**
 * Designer-shaped templates for `defineActionType` — GENERATED from two real
 * Flow Designer saves of a Custom Action Type (the PUT to
 * /api/now/processflow/action/action_types/{id}). Do not hand-edit the shapes:
 * they are the exact key sets the Designer sends, with values reset to the
 * step type's defaults. Record ids that belong to the STEP TYPE (each step
 * input's `id` is its sys_hub_step_type input definition) are kept; ids that
 * belong to one action (variable records, cids, uiUniqueIds) are blanked and
 * minted fresh per use.
 *
 * Regenerate from new captures rather than editing by hand.
 */

/* eslint-disable */

export interface StepTypeTemplate {
  /** sys_hub_step_type sys_id. */
  stepTypeId: string;
  /** The PUT body's DB_TYPE for this step type. */
  dbType: string;
  /** Outputs every step of this type exposes (`{{step[cid].<name>}}`). */
  builtinOutputs: Array<{ name: string; label: string; type: string }>;
  /** One PUT-shaped step with values at their defaults. */
  template: Record<string, unknown>;
}

export var STEP_TYPE_TEMPLATES: Record<"script" | "rest", StepTypeTemplate> = {
  "script": {
    "stepTypeId": "106afb6647032200b4fad7527c9a71e7",
    "dbType": "SCRIPT",
    "builtinOutputs": [
      {
        "name": "__step_status__",
        "label": "Step Status",
        "type": "object"
      }
    ],
    "template": {
      "DB_TYPE": "SCRIPT",
      "cid": "",
      "step_type_id": "106afb6647032200b4fad7527c9a71e7",
      "section": "",
      "label": "",
      "action": "",
      "order": 0,
      "inputs": [
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "instance",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "choice",
          "mandatory": true,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "74315b04b3201300176b051a16a8dc2b",
          "type_label": "Choice",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "Instance",
          "reference_display": "",
          "comments": null,
          "choiceOption": "3",
          "label": "Required Runtime",
          "defaultChoices": [
            {
              "label": "Instance",
              "value": "instance",
              "order": 1
            },
            {
              "label": "MID",
              "value": "mid",
              "order": 2
            },
            {
              "label": "Vanilla (Core JavaScript)",
              "value": "vanilla",
              "order": 3
            }
          ],
          "hint": "The runtime environment required to support the script. Select “Instance” to support the ServiceNow API or instance data. Select “MID” to support MID Server APIs. Select “Vanilla” to support only core JavaScript APIs.",
          "name": "required_run_time",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "maxsize": 40,
          "choices": [
            {
              "label": "Instance",
              "value": "instance",
              "order": 1
            },
            {
              "label": "MID",
              "value": "mid",
              "order": 2
            },
            {
              "label": "Vanilla (Core JavaScript)",
              "value": "vanilla",
              "order": 3
            }
          ],
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "required_run_time",
          "data_format": [
            {
              "label": "Instance",
              "value": "instance",
              "order": 1
            },
            {
              "label": "MID",
              "value": "mid",
              "order": 2
            },
            {
              "label": "Vanilla (Core JavaScript)",
              "value": "vanilla",
              "order": 3
            }
          ],
          "default_value": "instance",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 0,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "instance"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "any",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "choice",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "2c226939b3101300176b051a16a8dc83",
          "type_label": "Choice",
          "placeholder": "",
          "table": "",
          "order": 200,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "Any MID",
          "reference_display": "",
          "comments": null,
          "choiceOption": "3",
          "label": "Select MID Server Using",
          "defaultChoices": [
            {
              "label": "Any MID",
              "value": "any",
              "order": 1
            },
            {
              "label": "Use Connection Alias",
              "value": "use_connection_alias",
              "order": 2
            },
            {
              "label": "Use Inline Selection",
              "value": "define_connection_inline",
              "order": 3
            }
          ],
          "hint": "Select “Any MID” to run the script on any running MID server. Select “Use Connection Alias” to determine the MID from a Connection Alias. Select “Use Inline Connection” to define MID selection criteria inline.",
          "name": "mid_selection_type",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "connection": "true",
            "display_field": "connection_alias",
            "table_override": "basic_connection",
            "hide_edit": "true",
            "show_add": "true"
          },
          "maxsize": 40,
          "choices": [
            {
              "label": "Any MID",
              "value": "any",
              "order": 1
            },
            {
              "label": "Use Connection Alias",
              "value": "use_connection_alias",
              "order": 2
            },
            {
              "label": "Use Inline Selection",
              "value": "define_connection_inline",
              "order": 3
            }
          ],
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "mid_selection_type",
          "data_format": [
            {
              "label": "Any MID",
              "value": "any",
              "order": 1
            },
            {
              "label": "Use Connection Alias",
              "value": "use_connection_alias",
              "order": 2
            },
            {
              "label": "Use Inline Selection",
              "value": "define_connection_inline",
              "order": 3
            }
          ],
          "default_value": "any",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 1,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "any"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "id",
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "sys_alias",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "2b2ba571b3101300176b051a16a8dc8f",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 250,
          "internal_link": null,
          "ref_qual": "connection_type=sys_connection^type=connection^EQ",
          "defaultDisplayValue": null,
          "reference_display": "Connection & Credential Aliases",
          "comments": null,
          "choiceOption": "",
          "label": "Connection Alias",
          "hint": "Choose the Connection Alias to use",
          "name": "connection_alias",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "check_connection_admin_role": "true",
            "connection": "true",
            "display_field": "connection_alias",
            "table_override": "sys_connection",
            "hide_edit": "true",
            "show_add": "true"
          },
          "maxsize": 32,
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "connection_alias",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 2,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "string",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "28e4e579b3101300176b051a16a8dc0f",
          "type_label": "String",
          "placeholder": "",
          "table": "",
          "order": 300,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Host",
          "hint": "Enter target host where the script should run",
          "name": "host",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "maxsize": 120,
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "host",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 3,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "auto_select",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "choice",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "cbd1070373531010791f94596bf6a776",
          "type_label": "Choice",
          "placeholder": "",
          "table": "",
          "order": 350,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "Auto-Select MID Server",
          "reference_display": "",
          "comments": null,
          "choiceOption": "3",
          "label": "MID Selection",
          "defaultChoices": [
            {
              "label": "Auto-Select MID Server",
              "value": "auto_select",
              "order": 1
            },
            {
              "label": "Specific MID Server",
              "value": "specific_mid_server",
              "order": 2
            },
            {
              "label": "Specific MID Cluster",
              "value": "specific_mid_cluster",
              "order": 3
            }
          ],
          "hint": "",
          "name": "mid_selection",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "maxsize": 40,
          "choices": [
            {
              "label": "Auto-Select MID Server",
              "value": "auto_select",
              "order": 1
            },
            {
              "label": "Specific MID Server",
              "value": "specific_mid_server",
              "order": 2
            },
            {
              "label": "Specific MID Cluster",
              "value": "specific_mid_cluster",
              "order": 3
            }
          ],
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "mid_selection",
          "data_format": [
            {
              "label": "Auto-Select MID Server",
              "value": "auto_select",
              "order": 1
            },
            {
              "label": "Specific MID Server",
              "value": "specific_mid_server",
              "order": 2
            },
            {
              "label": "Specific MID Cluster",
              "value": "specific_mid_cluster",
              "order": 3
            }
          ],
          "default_value": "auto_select",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 4,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "auto_select"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "name",
          "defaultValue": "{\"display\":\"ALL\", \"value\":\"35aa573fd7802200bdbaee5b5e610375\"}",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "ecc_agent_application",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "f5e56d79b3101300176b051a16a8dce4",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 400,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "",
          "reference_display": "MID Server Application",
          "comments": null,
          "choiceOption": "",
          "label": "MID Application",
          "hint": "Choose MID Application required to select the correct MID server",
          "name": "application",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "maxsize": 32,
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "application",
          "data_format": "",
          "default_value": "{\"display\":\"ALL\", \"value\":\"35aa573fd7802200bdbaee5b5e610375\"}",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 5,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "{\"display\":\"ALL\", \"value\":\"35aa573fd7802200bdbaee5b5e610375\"}"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "capability_value",
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "ecc_agent_capability",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "7d36ed79b3101300176b051a16a8dceb",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 500,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "MID Server Capability",
          "comments": null,
          "choiceOption": "",
          "label": "Capabilities",
          "hint": "Choose MID capability required to select the correct MID server",
          "name": "capabilities",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "maxsize": 40,
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "capabilities",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 6,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "document_id",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "0d2db9e653310110d3a8ddeeff7b1208",
          "type_label": "Document ID",
          "placeholder": "",
          "table": "",
          "order": 550,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "MID Cluster",
          "hint": "",
          "name": "mid_cluster",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "maxsize": 32,
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "mid_cluster",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 7,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "document_id",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "f0d58b8373531010791f94596bf6a7be",
          "type_label": "Document ID",
          "placeholder": "",
          "table": "",
          "order": 550,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "MID Server",
          "hint": "",
          "name": "mid_server",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "maxsize": 32,
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "mid_server",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 8,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "name": "script",
          "value": "(function execute(inputs, outputs) {\n// ... code ...\n})(inputs, outputs);\n"
        }
      ],
      "extended_inputs": [],
      "extended_outputs": [],
      "error_handling_type": "EVAL_ERRORS"
    }
  },
  "rest": {
    "stepTypeId": "07a762fb47222200b4fad7527c9a7129",
    "dbType": "REST",
    "builtinOutputs": [
      {
        "name": "error_message",
        "label": "Error Message",
        "type": "string"
      },
      {
        "name": "response_headers",
        "label": "Response Headers",
        "type": "string"
      },
      {
        "name": "response_stream",
        "label": "Response Stream",
        "type": "string"
      },
      {
        "name": "status_code",
        "label": "Status Code",
        "type": "string"
      },
      {
        "name": "response_body",
        "label": "Response Body",
        "type": "string"
      },
      {
        "name": "error_code",
        "label": "Error Code",
        "type": "string"
      },
      {
        "name": "__step_status__",
        "label": "Step Status",
        "type": "object"
      }
    ],
    "template": {
      "DB_TYPE": "REST",
      "cid": "",
      "step_type_id": "07a762fb47222200b4fad7527c9a7129",
      "section": "",
      "label": "",
      "action": "",
      "order": 0,
      "inputs": [
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "use_connection_alias",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "choice",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "91e207d03b50030057a4a2e334efc4a0",
          "type_label": "Choice",
          "placeholder": "",
          "table": "",
          "order": 5,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "Use Connection Alias",
          "reference_display": "",
          "comments": null,
          "choiceOption": "3",
          "label": "Connection",
          "defaultChoices": [
            {
              "label": "Define Connection Inline",
              "value": "define_connection_inline",
              "order": 1
            },
            {
              "label": "Use Connection Alias",
              "value": "use_connection_alias",
              "order": 2
            }
          ],
          "hint": "Configure the step to select an existing Connection Alias or choose to define the connection inline",
          "name": "connection",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "choices": [
            {
              "label": "Define Connection Inline",
              "value": "define_connection_inline",
              "order": 1
            },
            {
              "label": "Use Connection Alias",
              "value": "use_connection_alias",
              "order": 2
            }
          ],
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "connection",
          "data_format": [
            {
              "label": "Define Connection Inline",
              "value": "define_connection_inline",
              "order": 1
            },
            {
              "label": "Use Connection Alias",
              "value": "use_connection_alias",
              "order": 2
            }
          ],
          "default_value": "use_connection_alias",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 0,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "use_connection_alias"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "manually",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "choice",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "bb61fcd3c7312300a150effeeb97638e",
          "type_label": "Choice",
          "placeholder": "",
          "table": "",
          "order": 10,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "Manually",
          "reference_display": "",
          "comments": null,
          "choiceOption": "3",
          "label": "Build Request",
          "defaultChoices": [
            {
              "label": "Manually",
              "value": "manually",
              "order": 1
            },
            {
              "label": "From OpenAPI specification - Deprecated",
              "value": "from_openapi",
              "order": 2
            },
            {
              "label": "From REST Message",
              "value": "from_snrestmessage",
              "order": 3
            }
          ],
          "hint": "",
          "name": "build_request",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "choices": [
            {
              "label": "Manually",
              "value": "manually",
              "order": 1
            },
            {
              "label": "From OpenAPI specification - Deprecated",
              "value": "from_openapi",
              "order": 2
            },
            {
              "label": "From REST Message",
              "value": "from_snrestmessage",
              "order": 3
            }
          ],
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "build_request",
          "data_format": [
            {
              "label": "Manually",
              "value": "manually",
              "order": 1
            },
            {
              "label": "From OpenAPI specification - Deprecated",
              "value": "from_openapi",
              "order": 2
            },
            {
              "label": "From REST Message",
              "value": "from_snrestmessage",
              "order": 3
            }
          ],
          "default_value": "manually",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 1,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "manually"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "id",
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": true,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "sys_alias",
          "dependent_on": "connection",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "262882f03b23320057a4a2e334efc4f0",
          "type_label": "Reference",
          "placeholder": "",
          "table": "use_connection_alias",
          "order": 10,
          "internal_link": null,
          "ref_qual": "type=connection^connection_type=http_connection^EQ",
          "defaultDisplayValue": null,
          "reference_display": "Connection & Credential Aliases",
          "comments": null,
          "choiceOption": "",
          "label": "Connection Alias",
          "hint": "Choose the Connection Alias to use",
          "name": "connection_alias",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "check_connection_admin_role": "true",
            "connection": "true",
            "display_field": "connection_alias",
            "table_override": "http_connection",
            "show_add": "true",
            "override_url": ""
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "connection_alias",
          "data_format": "use_connection_alias",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 2,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "id",
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "sys_alias",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "445c2a72b3701300176b051a16a8dcc2",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 10,
          "internal_link": null,
          "ref_qual": "type=credential^EQ",
          "defaultDisplayValue": null,
          "reference_display": "Connection & Credential Aliases",
          "comments": null,
          "choiceOption": "",
          "label": "Credential Alias",
          "hint": "",
          "name": "credential_alias",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "override_url": "wizard_view.do?sys_target=&sysparm_stack=_list.do&sysparm_wizardAction=sysverb_new&sysparm_parent=e74bf527c33213003f7cdb1122d3aed4",
            "display_field": "tag",
            "show_add": "true"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "credential_alias",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 3,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "false",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "boolean",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "e532afc12f101300a09a839fb18c95b9",
          "type_label": "True/False",
          "placeholder": "",
          "table": "",
          "order": 10,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "false",
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Use MID",
          "hint": "Send this request from a MID server",
          "name": "use_mid",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "hidden_for": "STORE_IN_AIS"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "use_mid",
          "data_format": "",
          "default_value": "false",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 4,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "false"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "auto_select",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "choice",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "a7d3fa4b73131010791f94596bf6a79a",
          "type_label": "Choice",
          "placeholder": "",
          "table": "",
          "order": 11,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "Auto-Select MID Server",
          "reference_display": "",
          "comments": null,
          "choiceOption": "3",
          "label": "MID Selection",
          "defaultChoices": [
            {
              "label": "Auto-Select MID Server",
              "value": "auto_select",
              "order": 1
            },
            {
              "label": "Specific MID Server",
              "value": "specific_mid_server",
              "order": 2
            },
            {
              "label": "Specific MID Cluster",
              "value": "specific_mid_cluster",
              "order": 3
            }
          ],
          "hint": "",
          "name": "mid_selection",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "choices": [
            {
              "label": "Auto-Select MID Server",
              "value": "auto_select",
              "order": 1
            },
            {
              "label": "Specific MID Server",
              "value": "specific_mid_server",
              "order": 2
            },
            {
              "label": "Specific MID Cluster",
              "value": "specific_mid_cluster",
              "order": 3
            }
          ],
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "mid_selection",
          "data_format": [
            {
              "label": "Auto-Select MID Server",
              "value": "auto_select",
              "order": 1
            },
            {
              "label": "Specific MID Server",
              "value": "specific_mid_server",
              "order": 2
            },
            {
              "label": "Specific MID Cluster",
              "value": "specific_mid_cluster",
              "order": 3
            }
          ],
          "default_value": "auto_select",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 5,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "auto_select"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "name",
          "defaultValue": "{\"display\":\"ALL\", \"value\":\"35aa573fd7802200bdbaee5b5e610375\"}",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "ecc_agent_application",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "f11ebf865f101300a09a2abd7f466652",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 12,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "",
          "reference_display": "MID Server Application",
          "comments": null,
          "choiceOption": "",
          "label": "MID Application",
          "hint": "Choose MID Application required to select the correct MID server",
          "name": "application",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "application",
          "data_format": "",
          "default_value": "{\"display\":\"ALL\", \"value\":\"35aa573fd7802200bdbaee5b5e610375\"}",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 6,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "{\"display\":\"ALL\", \"value\":\"35aa573fd7802200bdbaee5b5e610375\"}"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "capability_value",
          "defaultValue": "{\"display\":\"REST\", \"value\":\"18409d8007482000dada43c0d1021e8f\"}",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "ecc_agent_capability",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "c30a451d2f201300a09a839fb18c95b4",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 13,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "",
          "reference_display": "MID Server Capability",
          "comments": null,
          "choiceOption": "",
          "label": "Capabilities",
          "hint": "Choose MID capability required to select the correct MID server",
          "name": "capabilities",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "capabilities",
          "data_format": "",
          "default_value": "{\"display\":\"REST\", \"value\":\"18409d8007482000dada43c0d1021e8f\"}",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 7,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "{\"display\":\"REST\", \"value\":\"18409d8007482000dada43c0d1021e8f\"}"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "document_id",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "61d6b2cb73131010791f94596bf6a721",
          "type_label": "Document ID",
          "placeholder": "",
          "table": "",
          "order": 14,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "MID Server",
          "hint": "",
          "name": "mid_server",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "mid_server",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 8,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "display_name",
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "sys_openapi",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "c346f4d7c7312300a150effeeb976366",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 15,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "OpenAPI ",
          "comments": null,
          "choiceOption": "",
          "label": "API Source",
          "hint": "",
          "name": "api_source",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "api_source",
          "data_format": "",
          "default_value": "",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 9,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": true,
          "type": "url",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "connection_alias",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "a67a8ef03b23320057a4a2e334efc472",
          "type_label": "URL",
          "placeholder": "",
          "table": "{\"display\":\"x_cadso_email_spok.Email_Spoke_Connection\",\"value\":\"956cc622c3ee4a1085b196c4e401317e\",\"table\":\"sys_alias\",\"sys_id\":\"956cc622c3ee4a1085b196c4e401317e\"}",
          "order": 15,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Base URL",
          "hint": "Enter the base URL of the endpoint to use e.g. “https://api.service.com/v1/\"",
          "name": "base_url",
          "attributes": {
            "extract_from_alias": true,
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "base_url",
          "data_format": "",
          "default_value": "",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 10,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "display_value": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "document_id",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "cdfcf11053f10110d3a8ddeeff7b12e2",
          "type_label": "Document ID",
          "placeholder": "",
          "table": "",
          "order": 15,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "MID Cluster",
          "hint": "",
          "name": "mid_cluster",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "mid_cluster",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 11,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "name",
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": true,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "sys_openapi_operation",
          "dependent_on": "api_source",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "29c75782c7822300a150effeeb976338",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 16,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "OpenAPI  Operation",
          "comments": null,
          "choiceOption": "",
          "label": "API Operation",
          "hint": "",
          "name": "api_operation",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "hide_edit": "true"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "api_operation",
          "data_format": "",
          "default_value": "",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 12,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "string",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "3d090af03b23320057a4a2e334efc455",
          "type_label": "String",
          "placeholder": "",
          "table": "",
          "order": 20,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Resource Path",
          "hint": "Enter the path to the resource you are interacting with. This will be appended to the Base URL.",
          "name": "resource_path",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "resource_path",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 13,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "get",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "choice",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "e85b7ebf47222200b4fad7527c9a71e3",
          "type_label": "Choice",
          "placeholder": "",
          "table": "",
          "order": 25,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "GET",
          "reference_display": "",
          "comments": null,
          "choiceOption": "3",
          "label": "HTTP Method",
          "defaultChoices": [
            {
              "label": "GET",
              "value": "get",
              "order": 1
            },
            {
              "label": "POST",
              "value": "post",
              "order": 2
            },
            {
              "label": "PUT",
              "value": "put",
              "order": 3
            },
            {
              "label": "PATCH",
              "value": "patch",
              "order": 4
            },
            {
              "label": "DELETE",
              "value": "delete",
              "order": 5
            }
          ],
          "hint": "Select the HTTP method to use for this request",
          "name": "http_method",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "choices": [
            {
              "label": "GET",
              "value": "get",
              "order": 1
            },
            {
              "label": "POST",
              "value": "post",
              "order": 2
            },
            {
              "label": "PUT",
              "value": "put",
              "order": 3
            },
            {
              "label": "PATCH",
              "value": "patch",
              "order": 4
            },
            {
              "label": "DELETE",
              "value": "delete",
              "order": 5
            }
          ],
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "http_method",
          "data_format": [
            {
              "label": "GET",
              "value": "get",
              "order": 1
            },
            {
              "label": "POST",
              "value": "post",
              "order": 2
            },
            {
              "label": "PUT",
              "value": "put",
              "order": 3
            },
            {
              "label": "PATCH",
              "value": "patch",
              "order": 4
            },
            {
              "label": "DELETE",
              "value": "delete",
              "order": 5
            }
          ],
          "default_value": "get",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 14,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "get"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "name_values",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "4328e2fb47222200b4fad7527c9a7164",
          "type_label": "Name/Values",
          "placeholder": "",
          "table": "",
          "order": 25,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Query Parameters",
          "hint": "Enter the key/value pairs that should be sent as query parameters",
          "name": "query_params",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "advanced_inputs_config": "OMIT",
            "name_candrop": "true",
            "pwd2droppable": "true",
            "apply_json_val_encoding": "true",
            "is_scriptable": "true",
            "value_candrop": "true",
            "advanced_name_values": "true"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "query_params",
          "data_format": "",
          "default_value": "",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 15,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "name_values",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "371837f1c71003007b237f48cb9763b0",
          "type_label": "Name/Values",
          "placeholder": "",
          "table": "",
          "order": 30,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Headers",
          "hint": "Enter the key/value pairs that should be sent as HTTP headers",
          "name": "headers",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "advanced_inputs_config": "OMIT",
            "name_candrop": "true",
            "pwd2droppable": "true",
            "apply_json_val_encoding": "true",
            "is_scriptable": "true",
            "value_candrop": "true",
            "advanced_name_values": "true"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "headers",
          "data_format": "",
          "default_value": "",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 16,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "text",
          "show_ref_finder": false,
          "use_dependent": true,
          "type": "choice",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "http_method",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "bc79234a87d01300dd637d5e27cb0b24",
          "type_label": "Choice",
          "placeholder": "",
          "table": "get",
          "order": 40,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "Text",
          "reference_display": "",
          "comments": null,
          "choiceOption": "3",
          "label": "Request Type",
          "defaultChoices": [
            {
              "label": "Text",
              "value": "text",
              "order": 1
            },
            {
              "label": "Binary",
              "value": "binary",
              "order": 2
            },
            {
              "label": "Multipart",
              "value": "multi-part",
              "order": 3
            },
            {
              "label": "Form URL-Encoded",
              "value": "form-url-encoded",
              "order": 4
            }
          ],
          "hint": "Select the desired request type",
          "name": "request_type",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "choices": [
            {
              "label": "Text",
              "value": "text",
              "order": 1
            },
            {
              "label": "Binary",
              "value": "binary",
              "order": 2
            },
            {
              "label": "Multipart",
              "value": "multi-part",
              "order": 3
            },
            {
              "label": "Form URL-Encoded",
              "value": "form-url-encoded",
              "order": 4
            }
          ],
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "request_type",
          "data_format": "get",
          "default_value": "text",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 17,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "text"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "file_name",
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": true,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "sys_attachment",
          "dependent_on": "connection",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "8bf0dc9687141300dd637d5e27cb0b3c",
          "type_label": "Reference",
          "placeholder": "",
          "table": "use_connection_alias",
          "order": 45,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "Attachment",
          "comments": null,
          "choiceOption": "",
          "label": "Attachment",
          "hint": "Enter the Sys ID of the attachment to send as binary",
          "name": "attachment_id",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "attachment_id",
          "data_format": "use_connection_alias",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 18,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": true,
          "type": "multi_small",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "http_method",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "6c6073f1c71003007b237f48cb97633b",
          "type_label": "Multiple Line Small Text Area",
          "placeholder": "",
          "table": "get",
          "order": 45,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Request Body[Text]",
          "hint": "Enter the content to send in the body of the request",
          "name": "body",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "pwd2droppable": "true",
            "readonly": true
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "body",
          "data_format": "get",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 19,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": true,
          "type": "string",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "http_method",
          "data_structure": "",
          "readonly": true,
          "dynamic": null,
          "id": "3684ec4787d01300dd637d5e27cb0bcb",
          "type_label": "String",
          "placeholder": "",
          "table": "get",
          "order": 45,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "form_URL_encoded_map",
          "hint": "",
          "name": "form_URL_encoded_map",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "pwd2droppable": "true",
            "fd_hide_inline_script_widget": "true"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "form_URL_encoded_map",
          "data_format": "get",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 20,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": true,
          "type": "string",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "http_method",
          "data_structure": "",
          "readonly": true,
          "dynamic": null,
          "id": "b564608787d01300dd637d5e27cb0b7d",
          "type_label": "String",
          "placeholder": "",
          "table": "get",
          "order": 45,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "multipart_sources_string",
          "hint": "",
          "name": "multipart_sources_string",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "pwd2droppable": "true",
            "fd_hide_inline_script_widget": "true"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "multipart_sources_string",
          "data_format": "get",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 21,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "boolean",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "f9df589687301300735f7d5e27cb0b2d",
          "type_label": "True/False",
          "placeholder": "",
          "table": "",
          "order": 49,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Save As Attachment",
          "hint": "Select to save the response as an attachment",
          "name": "save_response_as_attachment",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "hidden_for": "DATASTREAM^STORE_IN_AIS"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "save_response_as_attachment",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 22,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "string",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "9458387787201300b3b67d5e27cb0b3b",
          "type_label": "String",
          "placeholder": "",
          "table": "",
          "order": 50,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Attachment File Name",
          "hint": "Enter the file name for the attachment",
          "name": "attachment_file_name",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "attachment_file_name",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 23,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "name",
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "sys_rest_message",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "b79bea415b101110ab933520b881c737",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 90,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "REST Message",
          "comments": null,
          "choiceOption": "",
          "label": "REST Message",
          "hint": "",
          "name": "rest_message",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "rest_message",
          "data_format": "",
          "default_value": "",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 24,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": true,
          "type": "document_id",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "table",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "6278787787201300b3b67d5e27cb0b94",
          "type_label": "Document ID",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Attachment File Record",
          "hint": "Enter the Sys ID of the record which the attachment will be associated with",
          "name": "attachment_file_record",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "attachment_file_record",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 25,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "integer",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "7a59009bc7522010820469467ec260c0",
          "type_label": "Integer",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Connection Timeout",
          "hint": "Timeout (milliseconds) value for this connection, overrides the global property.",
          "name": "connection_timeout",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "connection_timeout",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 26,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "false",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "boolean",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "15288f755bd24110ab933520b881c713",
          "type_label": "True/False",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "false",
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Honor Duplicate Headers",
          "hint": "",
          "name": "honor_duplicate_headers",
          "attributes": {
            "set_flag_on_republish": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "honor_duplicate_headers",
          "data_format": "",
          "default_value": "false",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 27,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": true
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "false",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "boolean",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "58715a1c53f22010d3a8ddeeff7b1248",
          "type_label": "True/False",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "false",
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Honor Duplicate Query Params",
          "hint": "",
          "name": "honor_duplicate_query_params",
          "attributes": {
            "set_flag_on_republish": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "honor_duplicate_query_params",
          "data_format": "",
          "default_value": "false",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 28,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": true
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "boolean",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "f1255aa377322300efb691572b106135",
          "type_label": "True/False",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Is Streaming",
          "hint": "",
          "name": "is_streaming",
          "attributes": {
            "visible_in_fd": "false",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "is_streaming",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 29,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "boolean",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "89fa6545cb200010a2fcb895634c9c3c",
          "type_label": "True/False",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Is Temporary Attachment",
          "hint": "",
          "name": "is_temporary_attachment",
          "attributes": {
            "visible_in_fd": "false",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "is_temporary_attachment",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 30,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "false",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "boolean",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "8e4f451f5b010110ab933520b881c72c",
          "type_label": "True/False",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": "false",
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Override Base URL",
          "hint": "",
          "name": "override_base_url",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "override_base_url",
          "data_format": "",
          "default_value": "false",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 31,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "false"
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "function_name",
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "sys_rest_message_fn",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "35bb6e415b101110ab933520b881c752",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "HTTP Method",
          "comments": null,
          "choiceOption": "",
          "label": "REST Message Function",
          "hint": "",
          "name": "rest_message_function",
          "attributes": {
            "disable_drop": "true",
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "rest_message_function",
          "data_format": "",
          "default_value": "",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 32,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "json",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "3c4d7367c7d32300a150effeeb9763a4",
          "type_label": "JSON",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "REST Metadata",
          "hint": "",
          "name": "rest_metadata",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "rest_metadata",
          "data_format": "",
          "default_value": "",
          "canDrop": false,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 33,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "table_name",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": true,
          "dynamic": null,
          "id": "a9adb007b3c21300176b051a16a8dc9a",
          "type_label": "Table Name",
          "placeholder": "",
          "table": "",
          "order": 100,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Table",
          "hint": "",
          "name": "table",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "is_scriptable": "false"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "table",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 34,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "boolean",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "321e31fd87803300a8cc7d5e27cb0b7a",
          "type_label": "True/False",
          "placeholder": "",
          "table": "",
          "order": 200,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Enable Retry Policy",
          "hint": "Select to enable the Retry Policy",
          "name": "enable_retry_policy",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "hidden_for": "STORE_IN_AIS"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "enable_retry_policy",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 35,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": null,
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "boolean",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "dynamic": null,
          "id": "324e357187c03300a8cc7d5e27cb0b43",
          "type_label": "True/False",
          "placeholder": "",
          "table": "",
          "order": 300,
          "internal_link": null,
          "ref_qual": "",
          "defaultDisplayValue": null,
          "reference_display": "",
          "comments": null,
          "choiceOption": "",
          "label": "Override Default Policy for Alias",
          "hint": "Select to override the default Retry Policy as per Connection Alias",
          "name": "override_default_policy_for_alias",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "override_default_policy_for_alias",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 36,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": ""
        },
        {
          "uiDisplayTypeLabel": null,
          "searchField": "name",
          "defaultValue": "",
          "show_ref_finder": false,
          "use_dependent": false,
          "type": "reference",
          "mandatory": false,
          "extended": false,
          "local": false,
          "sys_class_name": "",
          "reference": "sys_retry_policy",
          "dependent_on": "",
          "data_structure": "",
          "readonly": false,
          "children": [],
          "dynamic": null,
          "id": "37be397587c03300a8cc7d5e27cb0ba2",
          "type_label": "Reference",
          "placeholder": "",
          "table": "",
          "order": 400,
          "internal_link": null,
          "ref_qual": "connection_type=http_retry_conditions^EQ",
          "defaultDisplayValue": null,
          "reference_display": "Retry Policy",
          "comments": null,
          "choiceOption": "",
          "label": "Retry Policy",
          "hint": "Select Retry Policy",
          "name": "retry_policy",
          "attributes": {
            "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
            "override_url": "sys_retry_policy.do?&sysparm_clear_stack=true&sysparm_reference=sys_retry_policy&sysparm_domain_restore=false&sysparm_step_type=rest",
            "show_add": "true"
          },
          "columnName": "",
          "uiDisplayType": null,
          "field_name": "retry_policy",
          "data_format": "",
          "default_value": "",
          "canDrop": true,
          "nameToBeEdited": false,
          "parent": "",
          "depth": 1,
          "arrayPosition": 37,
          "uiUniqueId": "",
          "sourceUiUniqueId": "",
          "sourceType": "",
          "sourceId": "",
          "value": "{\"display\":\"Default HTTP Retry Policy\",\"value\":\"ef751ff07301330025d71afe2ff6a7f9\"}"
        }
      ],
      "extended_inputs": [],
      "extended_outputs": [
        {
          "attributes": {
            "isLocal": "true"
          },
          "local": true,
          "extended": true,
          "name": "sn_auth_token",
          "label": "Credential Value",
          "internal_type": "password2",
          "type": "password2",
          "displayLabel": "Credential Value",
          "dataType": "step",
          "step_name": "",
          "cid": "",
          "canDrag": true,
          "readonly": false,
          "reference": "",
          "mandatory": false,
          "parent": "",
          "order": 8
        }
      ],
      "error_handling_type": "EVAL_ERRORS"
    }
  }
};

/** A new action input (sys_hub_action_input) as the Designer first sends it. */
export var ACTION_INPUT_TEMPLATE: Record<string, unknown> = {
  "name": "",
  "type": "string",
  "type_label": "String",
  "order": 0,
  "path": 0,
  "mandatory": false,
  "params": [
    {
      "name": "reference",
      "label": "References Table",
      "type": "string"
    }
  ],
  "label": "",
  "nameToBeEdited": true,
  "uiUniqueId": "",
  "parent": "",
  "pillName": "",
  "pillLabel": "",
  "depth": 1,
  "arrayPosition": 0,
  "canDrop": true,
  "attributes": {
    "uiUniqueId": ""
  },
  "canDrag": true
};

/** A new action output (sys_hub_action_output) wired to a data pill. */
export var ACTION_OUTPUT_TEMPLATE: Record<string, unknown> = {
  "display_value": "",
  "uiDisplayTypeLabel": null,
  "searchField": null,
  "defaultValue": "",
  "show_ref_finder": false,
  "use_dependent": false,
  "type": "string",
  "mandatory": false,
  "extended": false,
  "local": false,
  "sys_class_name": "",
  "reference": "",
  "dependent_on": "",
  "data_structure": "",
  "readonly": false,
  "complexObjectValue": null,
  "dynamic": null,
  "id": "",
  "type_label": "String",
  "placeholder": null,
  "value": "",
  "table": "",
  "scriptActive": false,
  "order": 0,
  "internal_link": "",
  "ref_qual": "",
  "defaultDisplayValue": null,
  "reference_display": "",
  "comments": null,
  "choiceOption": "",
  "label": "",
  "script": {},
  "hint": "",
  "name": "",
  "scriptAsJsonString": null,
  "attributes": {
    "uiTypeLabel": "String",
    "element_mapping_provider": "com.glide.flow_design.action.data.FlowDesignVariableMapper",
    "pwd2droppable": "true",
    "uiType": "string",
    "uiUniqueId": "",
    "sourceUiUniqueId": "",
    "sourceType": "",
    "sourceId": ""
  },
  "maxsize": 8000,
  "columnName": "",
  "uiDisplayType": null,
  "nameToBeEdited": false,
  "parent": "",
  "depth": 1,
  "arrayPosition": 0,
  "uiUniqueId": "",
  "sourceUiUniqueId": "",
  "sourceType": "",
  "sourceId": "",
  "canDrop": true,
  "pillName": "",
  "pillLabel": "",
  "canDrag": true
};

/** A new script-step input variable (extended_inputs entry). */
export var STEP_EXT_INPUT_TEMPLATE: Record<string, unknown> = {
  "name": "",
  "readonly": false,
  "children": [],
  "value": "",
  "label": "",
  "type_label": "String",
  "type": "string",
  "mandatory": false,
  "order": 0
};

/** A new script-step output variable (extended_outputs entry). */
export var STEP_EXT_OUTPUT_TEMPLATE: Record<string, unknown> = {
  "name": "",
  "type": "string",
  "type_label": "String",
  "order": 0,
  "path": 0,
  "mandatory": false,
  "params": [
    {
      "name": "reference",
      "label": "References Table",
      "type": "string",
      "read_only": true,
      "invalidValue": false
    }
  ],
  "label": "",
  "nameToBeEdited": true,
  "extended": true,
  "attributes": {
    "sourceUiUniqueId": "",
    "sourceType": "",
    "sourceId": "",
    "uiUniqueId": ""
  },
  "parent": "",
  "depth": 1,
  "arrayPosition": 0,
  "uiUniqueId": "",
  "sourceUiUniqueId": "",
  "sourceType": "",
  "sourceId": "",
  "canDrop": true,
  "pillName": "",
  "pillLabel": "",
  "read_only": false,
  "readonly": false,
  "dataType": "step",
  "step_name": "",
  "cid": "",
  "canDrag": true,
  "reference": ""
};
